[project]
name = 'digital-will'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.digital-will]
path = 'contracts/digital-will.clar'
clarity_version = 3
epoch = 3.1

[contracts.asset-custody]
path = 'contracts/asset-custody.clar'
clarity_version = 3
epoch = 3.1

[contracts.emergency-recovery]
path = 'contracts/emergency-recovery.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
